# topology_configurations
topology.name: "DRPC"
component.spout_num: 3
component.page_bolt_num: 6
component.view_bolt_num: 9
component.user_bolt_num: 4
component.follower_bolt_num: 8

# drpc configurations
drpc.server: "intelidh-01"
drpc.server: "3772"

# kafka configurations
topic: "pageview"
client_id: "drpc"

# producer configurations
producer.class: "storm.benchmark.tools.producer.kafka.PageViewKafkaProducer"
producer.topology.name: "PageViewKafkaProducer"
producer.topic: topic
producer.component.spout_num: 4
producer.component.bolt_num: 4

