# topology configurations
topology.name: "TridentWordCount"
component.spout_num: 4
component.split_bolt_num: 8
component.count_bolt_num: 8

# kafka configurations
topic: "fileread"
client_id: "trident"

# producer configurations
producer.class: "storm.benchmark.tools.producer.kafka.FileReadKafkaProducer"
producer.topology.name: "FileReadKafkaProducer"
producer.topic: topic
producer.component.spout_num: 4
producer.component.bolt_num: 4